install:
	./gradlew clean installBootDist
run-dist:
	./build/install/app-boot/bin/app
build:
	./gradlew clean build
lint:
	./gradlew checkstyleMain
test:
	./gradlew test
report:
	./gradlew jacocoTestReport

.PHONY: build
